version: "3.9"
name: "adblock-and-dns"

services:
  pihole:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    
    depends_on:
      - unbound

    networks:
      dns-net:
        ipv4_address: 172.20.0.12

    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - ${PORT_PIHOLE_WEB:-80}:80
      - ${PORT_PIHOLE_WEBSSL:-443}:443
      - ${PORT_PIHOLE_TCP:-53}:53/tcp
      - ${PORT_PIHOLE_UDP:-53}:53/udp
    #  - ${PORT_PIHOLE_DHCP:-67}:67/udp # Only required if you are using Pi-hole as your DHCP server

    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      PIHOLE_DNS_: 172.20.0.13#5053
      DHCP_ACTIVE: ${PIHOLE_DHCP_ACTIVE:-false}
      PIHOLE_DOMAIN: ${PIHOLE_DOMAIN:-lan}
      DNSMASQ_LISTENING: 'all'

      TEMPERATUREUNIT: ${PIHOLE_TEMPUNIT:-c}
      WEBTHEME: ${PIHOLE_WEBTHEME:-default-dark}

    volumes:
      - ${CONFIGDIR}/pihole/pihole:/etc/pihole
      - ${CONFIGDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${CONFIGDIR}/pihole/resolv.conf:/etc/resolv.conf
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

    #cap_add:
    #  - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)


    healthcheck:
      test: ["CMD", "dig", "+norecurse", "+retry=0", "@127.0.0.1", "pi.hole"]
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest

    networks:
      dns-net:
        ipv4_address: 172.20.0.13

    volumes:
      - ${CONFIGDIR}/unbound:/opt/unbound/etc/unbound

    healthcheck:
      disable: true
    restart: unless-stopped

  orbital-sync:
    container_name: orbital-sync
    image: ghcr.io/mattwebbio/orbital-sync:1.8.1

    depends_on:
      - pihole

    environment:
      TZ: ${TZ}
      PRIMARY_HOST_BASE_URL: ${ORBITAL_PRIMARY_HOST_BASE_URL}
      PRIMARY_HOST_PATH: ${ORBITAL_PRIMARY_HOST_PATH}
      PRIMARY_HOST_PASSWORD: ${ORBITAL_PRIMARY_HOST_PASSWORD}

      INTERVAL_MINUTES: ${ORBITAL_SYNC_INTERVAL}
      UPDATE_GRAVITY: ${ORBITAL_UPDATE_GRAVITY}

      SECONDARY_HOST_1_BASE_URL: http://${FTLCONF_LOCAL_IPV4}:${PORT_PIHOLE_WEB}
      SECONDARY_HOST_1_PASSWORD: ${PIHOLE_PASSWORD} # I use the same password for both; change this if you want each pihole to have different passwords
      SECONDARY_HOST_1_PATH: ${ORBITAL_SECONDARY_HOST_1_PATH}

      SYNC_V5_WHITELIST: ${SYNC_V5_WHITELIST}
      SYNC_V5_REGEX_WHITELIST: ${SYNC_V5_REGEX_WHITELIST}
      SYNC_V5_BLACKLIST: ${SYNC_V5_BLACKLIST}
      SYNC_V5_REGEX_LIST: ${SYNC_V5_REGEX_LIST}
      SYNC_V5_AD_LIST: ${SYNC_V5_AD_LIST}
      SYNC_V5_CLIENT: ${SYNC_V5_CLIENT}
      SYNC_V5_GROUP: ${SYNC_V5_GROUP}
      SYNC_V5_AUDIT_LOG: ${SYNC_V5_AUDIT_LOG}
      SYNC_V5_STATIC_DHCP_LEASES: ${SYNC_V5_STATIC_DHCP_LEASES}
      SYNC_V5_LOCAL_DNS_RECORDS: ${SYNC_V5_LOCAL_DNS_RECORDS}
      SYNC_V5_LOCAL_CNAME_RECORDS: ${SYNC_V5_LOCAL_CNAME_RECORDS}
      SYNC_V5_FLUSH_TABLES: ${SYNC_V5_FLUSH_TABLES}


    restart: unless-stopped

networks:
  dns-net:
    name: dns-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16