version: "3.9"

services:

####################
# Brewing
####################
   tiltpi:
    container_name: TiltPi
    image: davismariotti/tiltpi-docker:1.1
    
    network_mode: host
    cap_add:
      - NET_ADMIN

    ports:
      - ${PORT_TILTPI:-1880}:1880

    environment:
      TZ: ${TZ}

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${CONFIGDIR}/tiltpi2:/data # node-reds data
    restart: unless-stopped
